# Generated by Django 4.2.16 on 2024-10-26 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_detail_chars_alter_product_slug_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
