# Generated by Django 4.2.16 on 2024-10-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_parketnaya_himia_product_sposob_ukladki_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=275, unique=True),
        ),
    ]
