# Generated by Django 4.2.16 on 2024-10-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon', models.ImageField(upload_to='service_icons/')),
                ('image', models.ImageField(upload_to='service_images/')),
            ],
        ),
    ]
