# Generated by Django 4.2.16 on 2024-10-27 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blocks/')),
                ('title', models.CharField(max_length=335)),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=225)),
            ],
        ),
        migrations.RemoveField(
            model_name='case',
            name='link',
        ),
        migrations.RemoveField(
            model_name='case',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=1, upload_to='blog/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.CreateModel(
            name='Youtube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('link', models.CharField(max_length=325)),
                ('items', models.ManyToManyField(blank=True, to='blog.caseitem')),
            ],
        ),
        migrations.CreateModel(
            name='Telegram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('link', models.CharField(max_length=325)),
                ('items', models.ManyToManyField(blank=True, to='blog.caseitem')),
            ],
        ),
        migrations.CreateModel(
            name='Instagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('link', models.CharField(max_length=325)),
                ('items', models.ManyToManyField(blank=True, to='blog.caseitem')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='inst',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.instagram'),
        ),
        migrations.AddField(
            model_name='case',
            name='tg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.telegram'),
        ),
        migrations.AddField(
            model_name='case',
            name='youtube',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.youtube'),
        ),
        migrations.AddField(
            model_name='post',
            name='blocks',
            field=models.ManyToManyField(blank=True, to='blog.block'),
        ),
    ]
