# Generated by Django 4.2.16 on 2024-10-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_slug_alter_service_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caseitem',
            name='link',
        ),
        migrations.AddField(
            model_name='caseitem',
            name='iframe',
            field=models.TextField(default='qwe'),
            preserve_default=False,
        ),
    ]
