# Generated by Django 4.2.16 on 2024-11-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_priceitem_price_service_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='blocks',
            field=models.ManyToManyField(blank=True, to='blog.block'),
        ),
    ]
