# Generated by Django 4.2.16 on 2024-11-02 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_product_slug'),
        ('blog', '0009_service_blocks'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorWorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=275)),
            ],
        ),
        migrations.CreateModel(
            name='FloorWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=275)),
                ('subtitle', models.CharField(max_length=275)),
                ('images', models.ManyToManyField(blank=True, to='shop.image')),
                ('items', models.ManyToManyField(blank=True, to='blog.floorworkitem')),
            ],
        ),
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=275)),
                ('image', models.ManyToManyField(blank=True, to='shop.image')),
            ],
        ),
    ]
