# Generated by Django 4.2.16 on 2024-11-17 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_category_options_alter_image_options_and_more'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advantage',
            options={'verbose_name': 'Преимущество', 'verbose_name_plural': 'Преимущества'},
        ),
        migrations.AlterModelOptions(
            name='block',
            options={'verbose_name': 'Блок', 'verbose_name_plural': 'Блоки'},
        ),
        migrations.AlterModelOptions(
            name='case',
            options={'verbose_name': 'Общий кейс', 'verbose_name_plural': 'Общий кейс'},
        ),
        migrations.AlterModelOptions(
            name='caseitem',
            options={'verbose_name': 'Кейс', 'verbose_name_plural': 'Кейсы'},
        ),
        migrations.AlterModelOptions(
            name='floorworkitem',
            options={'verbose_name': 'Описание', 'verbose_name_plural': 'Описание'},
        ),
        migrations.AlterModelOptions(
            name='floorworks',
            options={'verbose_name': 'Напольные работы', 'verbose_name_plural': 'Напольные работы'},
        ),
        migrations.AlterModelOptions(
            name='instagram',
            options={'verbose_name': 'Инстаграм', 'verbose_name_plural': 'Инстаграм'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'verbose_name': 'Цена', 'verbose_name_plural': 'Цены'},
        ),
        migrations.AlterModelOptions(
            name='priceitem',
            options={'verbose_name': 'Цена услуги', 'verbose_name_plural': 'Цены услуг'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterModelOptions(
            name='telegram',
            options={'verbose_name': 'Телеграм', 'verbose_name_plural': 'Телеграм'},
        ),
        migrations.AlterModelOptions(
            name='youtube',
            options={'verbose_name': 'Ютуб', 'verbose_name_plural': 'Ютуб'},
        ),
        migrations.AlterField(
            model_name='advantage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.image', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='advantage',
            name='text',
            field=models.CharField(max_length=275, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='block',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blocks/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='block',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='block',
            name='title',
            field=models.CharField(max_length=335, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='case',
            name='inst',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.instagram', verbose_name='Инстаграм'),
        ),
        migrations.AlterField(
            model_name='case',
            name='tg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.telegram', verbose_name='Телеграм'),
        ),
        migrations.AlterField(
            model_name='case',
            name='youtube',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.youtube', verbose_name='Ютуб'),
        ),
        migrations.AlterField(
            model_name='caseitem',
            name='title',
            field=models.CharField(max_length=225, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='floorworkitem',
            name='name',
            field=models.CharField(max_length=275, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='floorworks',
            name='images',
            field=models.ManyToManyField(blank=True, to='shop.image', verbose_name='Изображения'),
        ),
        migrations.AlterField(
            model_name='floorworks',
            name='items',
            field=models.ManyToManyField(blank=True, to='blog.floorworkitem', verbose_name='Описания'),
        ),
        migrations.AlterField(
            model_name='floorworks',
            name='subtitle',
            field=models.CharField(max_length=275, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='floorworks',
            name='title',
            field=models.CharField(max_length=275, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='instagram',
            name='items',
            field=models.ManyToManyField(blank=True, to='blog.caseitem', verbose_name='Кейсы'),
        ),
        migrations.AlterField(
            model_name='instagram',
            name='link',
            field=models.CharField(max_length=325, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='instagram',
            name='title',
            field=models.CharField(max_length=225, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='post',
            name='blocks',
            field=models.ManyToManyField(blank=True, to='blog.block', verbose_name='Блоки'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='blog/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=275, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=225, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='price',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='price_items', to='blog.priceitem', verbose_name='Цены'),
        ),
        migrations.AlterField(
            model_name='price',
            name='title',
            field=models.CharField(max_length=335, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='priceitem',
            name='name',
            field=models.CharField(max_length=335, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='priceitem',
            name='price',
            field=models.IntegerField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='service',
            name='blocks',
            field=models.ManyToManyField(blank=True, to='blog.block', verbose_name='Блоки'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.ImageField(upload_to='service_icons/', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to='service_images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='service',
            name='prices',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.price', verbose_name='Цены'),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, max_length=275, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='service',
            name='subtitle',
            field=models.CharField(max_length=275, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=225, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='telegram',
            name='items',
            field=models.ManyToManyField(blank=True, to='blog.caseitem', verbose_name='Кейсы'),
        ),
        migrations.AlterField(
            model_name='telegram',
            name='link',
            field=models.CharField(max_length=325, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='telegram',
            name='title',
            field=models.CharField(max_length=225, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='youtube',
            name='items',
            field=models.ManyToManyField(blank=True, to='blog.caseitem', verbose_name='Кейсы'),
        ),
        migrations.AlterField(
            model_name='youtube',
            name='link',
            field=models.CharField(max_length=325, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='youtube',
            name='title',
            field=models.CharField(max_length=225, verbose_name='Название'),
        ),
    ]
