# Generated by Django 4.2.16 on 2024-11-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_advantage_options_alter_block_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО отправителя')),
                ('phone_number', models.CharField(max_length=45, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Эл почта')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
