# Generated by Django 4.2.16 on 2024-11-24 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
    ]
