# Generated by Django 4.2.16 on 2024-11-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_question_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceitem',
            name='name',
            field=models.CharField(max_length=335, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='priceitem',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
    ]
