# Generated by Django 4.2.16 on 2024-12-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_priceitem_name_alter_priceitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='title',
            field=models.CharField(blank=True, max_length=335, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='service',
            name='blocks',
            field=models.ManyToManyField(blank=True, related_name='service', to='blog.block', verbose_name='Блоки'),
        ),
    ]
