# Generated by Django 4.2.16 on 2025-01-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_block_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseitem',
            name='link',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='caseitem',
            name='iframe',
            field=models.TextField(blank=True),
        ),
    ]
