# Generated by Django 4.2.16 on 2025-01-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_link_caseitem_image_link_caseitem_post_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caseitem',
            name='image_link',
        ),
        migrations.AddField(
            model_name='caseitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
