# Generated by Django 4.2.16 on 2025-01-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_rename_image_caseitem_image_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorWorksImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='floor_images', verbose_name='Изображение')),
                ('link', models.URLField(blank=True, max_length=225, null=True)),
            ],
        ),
    ]
