# Generated by Django 4.2.16 on 2024-10-25 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('slug', models.CharField(max_length=225)),
                ('artikul', models.IntegerField()),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('size', models.JSONField()),
                ('chars', models.JSONField()),
                ('images', models.JSONField()),
                ('is_trend', models.BooleanField(default=False)),
                ('is_hit', models.BooleanField(default=False)),
                ('is_best', models.BooleanField(default=False)),
                ('sub_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.subcategory')),
            ],
        ),
    ]
