# Generated by Django 4.2.16 on 2024-11-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='useful_product',
            field=models.ManyToManyField(blank=True, to='shop.product'),
        ),
    ]
