# Generated by Django 4.2.16 on 2024-11-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_useful_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='squared_metres',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
