# Generated by Django 4.2.16 on 2024-11-17 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_squared_metres'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'ПодКатегория', 'verbose_name_plural': 'ПодКатегории'},
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=225, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='artikul',
            field=models.IntegerField(verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='product',
            name='chars',
            field=models.JSONField(verbose_name='Описания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='detail_chars',
            field=models.JSONField(verbose_name='Детали продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(blank=True, to='shop.image', verbose_name='Изображения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_best',
            field=models.BooleanField(default=False, verbose_name='Лучший'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_hit',
            field=models.BooleanField(default=False, verbose_name='Хит'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_trend',
            field=models.BooleanField(default=False, verbose_name='Тренд'),
        ),
        migrations.AlterField(
            model_name='product',
            name='parketnaya_himia',
            field=models.TextField(blank=True, null=True, verbose_name='Паркетная Химия'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale',
            field=models.IntegerField(default=0, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена после скидки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.JSONField(verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=275, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sposob_ukladki',
            field=models.TextField(blank=True, null=True, verbose_name='Способ укладки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='squared_metres',
            field=models.FloatField(blank=True, null=True, verbose_name='Количество метров в упаковке'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.subcategory', verbose_name='ПодКатегория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=225, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='useful_product',
            field=models.ManyToManyField(blank=True, to='shop.product', verbose_name='Полезные товары'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='shop.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='title',
            field=models.CharField(max_length=225, verbose_name='Название'),
        ),
    ]
