# Generated by Django 4.2.16 on 2024-11-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_category_options_alter_image_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='chars',
            field=models.JSONField(blank=True, null=True, verbose_name='Описания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='detail_chars',
            field=models.JSONField(blank=True, null=True, verbose_name='Детали продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.JSONField(blank=True, null=True, verbose_name='Размер'),
        ),
    ]
