# Generated by Django 4.2.16 on 2025-01-05 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_product_chars_alter_product_detail_chars_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225, verbose_name='Название')),
                ('file', models.FileField(blank=True, null=True, upload_to='attachments/')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='volume',
            field=models.JSONField(blank=True, null=True, verbose_name='Объем и цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='product',
            name='attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.attachment', verbose_name='Ссылка на файл'),
        ),
    ]
