# Generated by Django 4.2.16 on 2025-01-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_attachment_product_volume_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='title',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Название'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='attachment',
        ),
        migrations.AddField(
            model_name='product',
            name='attachment',
            field=models.ManyToManyField(blank=True, to='shop.attachment', verbose_name='Ссылка на файл'),
        ),
    ]
