# Generated by Django 4.2.16 on 2025-01-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_attachment_title_remove_product_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=1, verbose_name='Цена'),
        ),
    ]
