# Generated by Django 4.2.16 on 2024-11-10 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
