# Generated by Django 4.2.16 on 2024-11-17 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_category_options_alter_image_options_and_more'),
        ('blog', '0002_alter_advantage_options_alter_block_options_and_more'),
        ('orders', '0002_productorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productorder',
            options={'verbose_name': 'Заказ продукта', 'verbose_name_plural': 'Заказы продуктов'},
        ),
        migrations.AlterModelOptions(
            name='serviceorder',
            options={'verbose_name': 'Заказ услуги', 'verbose_name_plural': 'Заказы услуг'},
        ),
        migrations.AddField(
            model_name='productorder',
            name='lift',
            field=models.CharField(default='qwe', max_length=255, verbose_name='Подъем'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productorder',
            name='comments_on_order',
            field=models.TextField(verbose_name='Комментарии по заказу'),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='delivery_on_order',
            field=models.TextField(verbose_name='Доставка по заказу'),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='order_items',
            field=models.ManyToManyField(blank=True, to='shop.product', verbose_name='Продукты в заказе'),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='phone_number',
            field=models.CharField(max_length=255, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='comments_on_order',
            field=models.TextField(verbose_name='Комментарии по заказу'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='delivery_on_order',
            field=models.TextField(verbose_name='Доставка по заказу'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='phone_number',
            field=models.CharField(max_length=255, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.price', verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.service', verbose_name='Услуга'),
        ),
    ]
