# Generated by Django 4.2.16 on 2024-11-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_productorderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpressCalc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('squared_metres', models.PositiveIntegerField(verbose_name='Площадь помещения')),
                ('parquet_age', models.PositiveIntegerField(verbose_name='Возраст паркета')),
                ('phone_number', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('photo', models.ImageField(upload_to='ExpressCalcPhotos/', verbose_name='Фото')),
            ],
        ),
    ]
