# Generated by Django 4.2.16 on 2024-11-24 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0005_expresscalc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expresscalc',
            options={'verbose_name': 'Расчет', 'verbose_name_plural': 'Расчеты'},
        ),
        migrations.AddField(
            model_name='productorder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
