# Generated by Django 4.2.16 on 2024-11-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_expresscalc_options_productorder_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='order_items',
            field=models.ManyToManyField(blank=True, to='orders.productorderitem', verbose_name='Продукты в заказе'),
        ),
    ]
