# Generated by Django 4.2.16 on 2024-11-30 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_priceitem_name_alter_priceitem_price'),
        ('orders', '0007_alter_productorder_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.priceitem', verbose_name='Цена'),
        ),
    ]
