# Generated by Django 4.2.16 on 2024-11-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_serviceorder_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='lift',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подъем'),
        ),
    ]
