# Generated by Django 4.2.16 on 2025-01-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_serviceorder_lift'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorderitem',
            name='volume',
            field=models.PositiveIntegerField(default=1, verbose_name='Объем'),
            preserve_default=False,
        ),
    ]
