# Generated by Django 4.2.16 on 2025-01-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_productorderitem_volume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorderitem',
            name='volume',
        ),
        migrations.AddField(
            model_name='productorderitem',
            name='artikul',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Артикул'),
        ),
    ]
